### ISSUE TITLE
Setup defaults to reflect native behavior in best possible way

### ISSUE THREAD

**Issue by medikoo** [MatAtBread/nodent#100]
We're using `nodent` as a temporary step.

Normally we run our code in Node v8 (without any transpilation overhead). However as at this point we also need to run our code in Node.js v6 environments, for which we transpile iasync/await with nodent. This step is scheduled to be removed once when we'd be able to rely on Node v8 in all cases.

Recently we were surprised to learn that Nodent doesn't by _default_ follow async/await spec, and that needs to be forced with extra options. We had problem specifically with `wrapAwait` not being applied. Additionally we updated our setup to have `noNodentExtension: true` (altought that probably didn't incur any side effects for us)

I think it'll be more intuitive if that's a default setup for nodent (?)

**Comment by matAtWork** [comment]
While it might be intuitive, it would break all legacy code that uses the current default options, which would make such a change very unpopular. I don't know how you're invoking nodent (pre-compilation, or transpilation on the fly), but I can recommend putting the default options in your package.json which would work for the entire project.

**Comment by medikoo** [comment]
@matAtWork we updated options, and it works on now for us.  Still it was surprising that we had to set this options.

Change proposed here, if added, should come with next major, so it shouldn't break any legacy code.

Given current state, there's a feeling that library tries to propose it's own variant of async/await, and treats standard as second citizen. I thought it's main goal is just to provide _native_ async/await transpilation to envs that do not support it natively.

**Comment by matAtWork** [comment]
I appreciate it might look like that way, however `nodent` pre-dates the date the spec was published by over a year and there is a significant legacy. It has become "spec-compliant" over time, but it is necessary to specify that requirement via options. 

Feel free to fork or write a CLI that invokes `nodent-compiler` with your preferred options - it's open source so you can modify it to meet your needs.

Finally, one early design goal of nodent was performance, and the `wrapAwait` option (which meets the requirement in the spec) has a significant performance impact.

**Comment by medikoo** [comment]
Thanks @matAtWork for explanations. That's fair. We can live with it :)

Generally native promises come with performance penalties, same with native async/await, but I think it doesn't affect in anyway most real world cases.
