### ISSUE TITLE
Hand-written-like promises.

### ISSUE THREAD

**Issue by trusktr** [MatAtBread/nodent#101]
This is much better than regenerator, but I'm still wishing I had something that could compile async/await to hand-written-like functions.

For example, if we take this async function:

```js
        async _waitForMountThenResolveMountPromise() {
            if (this._awaitingScenePromise) return
            try {
                this._awaitingScenePromise = true
                await this._getScenePromise()
                await this._scene.mountPromise
            } catch (e) {
                if (e == 'mountcancel') return
                else throw e
            } finally {
                this._awaitingScenePromise = false
            }

            this._mounted = true
            this._resolveMountPromise()
            this._elementManager.shouldRender()
        }
```

we could re-write it using promises like this:

```js
        _waitForMountThenResolveMountPromise() {
            if (this._awaitingScenePromise) return Promise.resolve()

            const logic = () => {
                this._mounted = true
                this._resolveMountPromise()
                this._elementManager.shouldRender()
            }

            this._awaitingScenePromise = true

            let possibleError = undefined

            // try
            return this._getScenePromise()
            .then(() => this._scene.mountPromise)

                .then(logic)

            // catch
            .catch(e => {
                if (e == 'mountcancel') return
                else possibleError = e
            })

            // finally
            .then(() => {
                this._awaitingScenePromise = false

                if (possibleError) throw possibleError
            })
        }
```

This seems to be more light weight than the smallest possible output from nodent:

```js
_waitForMountThenResolveMountPromise() {
    return new Promise((function ($return, $error) {
        var $Try_1_Finally = (function ($Try_1_Exit) {
            return (function ($Try_1_Value) {
                this._awaitingScenePromise = false;
                return $Try_1_Exit && $Try_1_Exit.call(this, $Try_1_Value);
            }).$asyncbind(this, $error);
        }).$asyncbind(this);
        if (this._awaitingScenePromise) 
            return $return();
        var $Try_1_Post = (function () {
            this._mounted = true;
            this._resolveMountPromise();
            this._elementManager.shouldRender();
            return $return();
        }).$asyncbind(this, $error);
        var $Try_1_Catch = (function (e) {
            if (e == 'mountcancel') 
                return $Try_1_Finally($return)();
             else 
                throw e;
            return $Try_1_Finally($Try_1_Post)();
        }).$asyncbind(this, $Try_1_Finally($error));
        try {
            this._awaitingScenePromise = true;
            return this._getScenePromise().then((function ($await_2) {
                return this._scene.mountPromise.then((function ($await_3) {
                    return $Try_1_Finally($Try_1_Post)();
                }).$asyncbind(this, $Try_1_Catch), $Try_1_Catch);
            }).$asyncbind(this, $Try_1_Catch), $Try_1_Catch);
        } catch (e) {
            $Try_1_Catch(e)
        }
    }).$asyncbind(this));
}
```

([here's](http://nodent.mailed.me.uk/#async%20function%20_waitForMountThenResolveMountPromise()%20%7B%0A%20%20%20%20if%20(this._awaitingScenePromise)%20%0A%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20this._awaitingScenePromise%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20await%20this._getScenePromise()%3B%0A%20%20%20%20%20%20%20%20await%20this._scene.mountPromise%3B%0A%20%20%20%20%7D%20catch%20(e)%20%7B%0A%20%20%20%20%20%20%20%20if%20(e%20%3D%3D%20'mountcancel')%20%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20%20%20%20%20%20else%20%0A%20%20%20%20%20%20%20%20%20%20%20%20throw%20e%3B%0A%20%20%20%20%7D%20finally%20%7B%0A%20%20%20%20%20%20%20%20this._awaitingScenePromise%20%3D%20false%3B%0A%20%20%20%20%7D%0A%20%20%20%20this._mounted%20%3D%20true%3B%0A%20%20%20%20this._resolveMountPromise()%3B%0A%20%20%20%20this._elementManager.shouldRender()%3B%0A%7D%0A%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Afalse%2C%22es6target%22%3Afalse%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D) in the nodent "repl")

---

It would awesome if we could compile code so that all possible code paths were spec-compliant, but that not all spec-compliant need to be present in the output code if those things will never happen.

In my handwritten code, f.e., all the use cases are satisfied, and both my hand written version and the async version work exactly the same (at least I haven't had any issues yet).

But you get the idea. Do you think something like this is possible; converting async functions into the same code that you'd write by hand had you only Promises?

**Comment by matAtWork** [comment]
In all honesty, probably not. The analysis of code paths in JS is non-trivial, and in particular try...catch...finally is a nightmare (eg: `try { bad_code_ref() ; } catch (ex) { return ex } finally { return "done" }`.

The only reasonable optimization I could envisage would be collapse the nested `(promise).then(...)` calls into a chain of `then(...)` calls, but it would have to be broken regularly by code with alternate paths, which in many cases like yours would render the optimization useless

**Comment by matAtWork** [comment]
I'm going to close this as there's no action. If you feel I've misunderstood, please re-open
