### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Silviu-Caprar** [MatAtBread/nodent#104]
Hello there,

Can you please specify which BSD-2-Clause applies for nodent ?
I am interested specifically for version 3.0.17.

Thank you,
Silviu

**Comment by matAtWork** [comment]
I should amend the package.json. As far as I am concerned, nodent, nodent-compiler, fast-async and nodent-runtime are licensed under MIT, as in https://github.com/MatAtBread/nodent-runtime/blob/master/LICENSE.

**Comment by Silviu-Caprar** [comment]
Does this mean MIT License applies on node v.3.0.17 as well ?

**Comment by matAtWork** [comment]
Yes. Although I would recommend using the latest version as quite a few bugs were fixed after v3.0.17

**Comment by Silviu-Caprar** [comment]
Thank you very much.
