### ISSUE TITLE
[Feature request] optional generation of `.finally` block

### ISSUE THREAD

**Issue by le0nik** [MatAtBread/nodent#106]
This would be very useful for bluebird's cancellation: http://bluebirdjs.com/docs/api/cancellation.html where `.finally` is always called even on cancelled promises, other callbacks are not.

**Comment by matAtWork** [comment]
At the moment I have no personal need for this, and it's a long way from the spec, so I have no plans to implement this.

If you wish to fork and make a PR, I'll look into making it an optional feature.

**Comment by le0nik** [comment]
Sure I'll look into it, thx for reply.
