### ISSUE TITLE
Nodent compiler cannot output rest/spread properties

### ISSUE THREAD

**Issue by mtgrosser** [MatAtBread/nodent#107]
Using the spread operator in object literals currently produces a  `SyntaxError: Unexpected token`:

```js
compiler.compile('var foo = { ...spread(), bar: 42 }')
```
Support for rest/spread properties has been added to acorn just recently: https://github.com/acornjs/acorn/pull/658

However, a [hard-coded property type in nodent-compiler/lib/output.js](https://github.com/MatAtBread/nodent-compiler/blob/2fbcf572ba287315672952eb6a3be6bcb504a73a/lib/output.js#L667) prevents them from being rendered.

The following change solved the issue for me:

```diff
--- a/vendor/node_modules/nodent-compiler/lib/output.js
+++ b/vendor/node_modules/nodent-compiler/lib/output.js
@@ -664,7 +664,7 @@ var traveler = {
             for (var i = 0; ; ) {
                 property = properties[i];
                 state.write(null, propertyIndent);
-                this.out(property, state,'Property');
+                this.out(property, state, property.type);
                 if (++i < length)
                     state.write(node, ',', lineEnd);
                  else
```

**Comment by matAtWork** [comment]
Thanks for pointing this out. 

Published on npm as nodent@3.1.8
