### ISSUE TITLE
[Bug]: promise is never resolved in case of using `await` in `if` block inside of `catch`

### ISSUE THREAD

**Issue by le0nik** [MatAtBread/nodent#109]
fast-async@6.3.6
nodent-transform@3.2.3
nodent-compiler@3.2.2

```js
async function test() {
    try {
        await Promise.reject(new Error('err'));
    } catch (error) {
        if (true) {
            await Promise.resolve();
        }
    } finally {
        console.log('finally');
    }
}
```

The problem is in an `if` block inside of `catch`. It generates an empty `try {} catch ($boundEx)` inside of `$Try_1_Catch` which results in `$Try_1_Finally` never being called and promise never being resolved.

Line 22 here:
http://nodent.mailed.me.uk/#async%20function%20test()%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20await%20Promise.reject(new%20Error('err'))%3B%0A%20%20%20%20%7D%20catch%20(error)%20%7B%0A%20%20%20%20%20%20%20%20if%20(true)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20await%20Promise.resolve()%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20finally%20%7B%0A%20%20%20%20%20%20%20%20console.log('finally')%3B%0A%20%20%20%20%7D%0A%7D%0A%0Atest()%3B~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22native%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

If you run this code `finally` block is never reached

**Comment by le0nik** [comment]
For some reason it started happening after updating `babel-core` from `6.26.0` to `6.26.3`(or even `6.26.2`).

**Comment by MatAtBread** [comment]
Thanks for the report. I'll try and work out why this regression happens.

**Comment by MatAtBread** [comment]
Quick update: this issue is block-nesting. If you remove the block enclosing the `if` body, it works. I have an idea why this might have occurred, I just need to add it to my test cases and find a fix(!)

**Comment by le0nik** [comment]
Thx. Can confirm that it's working correctly now.

**Comment by MatAtBread** [comment]
You're welcome - thanks for the report and test case
