### ISSUE TITLE
test not working

### ISSUE THREAD

**Issue by matthiasg** [MatAtBread/nodent#11]
we are experimenting a little more with nodent, especially in integration with babel for all the other es6 stuff.

to begin with we tried a very simple script on your online tool:

http://nodent.mailed.me.uk/#%2F%2FES7%20code%0AasyncTest.then(()%20%3D%3E%20console.log('done'))%3B%0Aasync%20function%20asyncTest()%20%7B%0A%20%20%20%20let%20asyncTest%20%3D%20await%20test()%3B%0A%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20%20%20var%20t%20%3D%20t%5B10%5D%3B%0A%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20t.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20test2()%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20await%20wait(1000)%3B%0A%7D%0A%0Afunction%20wait(time)%20%7B%0A%20%20%20%20return%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setTimeout(resolve%2C%20time)%3B%0A%20%20%20%20%7D)%3B%0A%7D%0A%0Afunction%20test2()%20%7B%7D%0A%0A

this compiles just fine but executing the compiled code seems not to work complaining about let etc..

i was under the impression that nodent would only compile async and await and leave the es6 features untouched (and thus let it be compiled by babel down to es3/5)

**Comment by matAtWork** [comment]
Correct - it should leave the ES6 stuff untouched. On my browser (Chrome) I get the error:
    
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

This is from the browser - not nodent. Put

    "use strict"; 

Also, your code has a few bugs: 'asyncTest.then' should be 'asyncTest().then'. 'var t = t[10]' is broken, and you need a return in asyncTest.

Here's a fixed version:

http://nodent.mailed.me.uk/#%22use%20strict%22%3B%0A%0AasyncTest().then(()%20%3D%3E%20console.log('done'))%3B%0Aasync%20function%20asyncTest()%20%7B%0A%20%20%20%20let%20asyncTest%20%3D%20await%20test()%3B%0A%20%20%20%20return%20%3B%0A%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20%20%20var%20t%20%3D%20%5B10%5D%3B%0A%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20t.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20test2()%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20await%20wait(1000)%3B%0A%7D%0A%0Afunction%20wait(time)%20%7B%0A%20%20%20%20return%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setTimeout(resolve%2C%20time)%3B%0A%20%20%20%20%7D)%3B%0A%7D%0A%0Afunction%20test2()%20%7B%7D%0A%0A

**Comment by matthiasg** [comment]
Sorry I copied the unfixed version ... But good to know then I can use Babel afterwards...

I didn't add 'use strict' because es6/7 implies that and I missed that it wasn't generated.

----- Ursprüngliche Nachricht -----
Von: "Matt W" <notifications@github.com>
Gesendet: ‎12.‎10.‎2015 12:28
An: "MatAtBread/nodent" <nodent@noreply.github.com>
Cc: "matthiasg" <mgt576@gmail.com>
Betreff: Re: [nodent] test not working (#11)

Correct - it should leave the ES6 stuff untouched. On my browser (Chrome) I get the error:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
This is from the browser - not nodent. Put
"use strict"; 
Also, your code has a few bugs: 'asyncTest.then' should be 'asyncTest().then'. 'var t = t[10]' is broken, and you need a return in asyncTest.
Here's a fixed version:
http://nodent.mailed.me.uk/#%22use%20strict%22%3B%0A%0AasyncTest().then(()%20%3D%3E%20console.log('done'))%3B%0Aasync%20function%20asyncTest()%20%7B%0A%20%20%20%20let%20asyncTest%20%3D%20await%20test()%3B%0A%20%20%20%20return%20%3B%0A%7D%0A%0Aasy nc%20function%20test()%20%7B%0A%20%20%20%20var%20t%20%3D%20%5B10%5D%3B%0A%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20t.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20test2()%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20await%20wait(1000)%3B%0A%7D%0A%0Afunction%20wait(time)%20%7B%0A%20%20%20%20return%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setTimeout(resolve%2C%20time)%3B%0A%20%20%20%20%7D)%3B%0A%7D%0A%0Afunction%20test2()%20%7B%7D%0A%0A
