### ISSUE TITLE
nodent-compiler - add support for integrating nodent-runtime

### ISSUE THREAD

**Issue by skerit** [MatAtBread/nodent#111]
The `nodent-compiler` instruction is a bit confusing regarding compiling scripts for browsers.

> nodent-runtime must be available to generated code if es7 or generators is set, or noRuntime is falsy.

I took this to mean: `nodent-runtime` is not needed when `noRuntime` is truthy, but that's not correct either. 

Then I thought, maybe I just need to require `nodent-runtime` and the compiler will add it on-the-fly, but no. (Even though the `nodent` package `generateRequestHandler` DOES do that)

So I wish the compiler could be configured to act more like `generateRequestHandler`.

It's just a thought, though. I eventually added a `Promise` polyfill and that was that.

**Comment by MatAtBread** [comment]
It sounds like you want `nodent`, not `nodent-compiler` which handles all this for you. The compiler was split out from `nodent` a while back so it could be used in other envs, like the Babel plugin `fast-async`.

Of course, your use-case might be different?
