### ISSUE TITLE
es7.annotations

### ISSUE THREAD

**Issue by matthiasg** [MatAtBread/nodent#12]
In our project we introduced es7 annotations a few weeks ago since these allow us to remove duplicate DI definitions.

It would be great if the nodent ast compiler could simply ignore these lines and pass them through (we only use them in single lines and not to decorate variables yet). We cannot really filter these out since the sourcemaps would be screwed up.

Code Excerpt:
```
import {annotate} from 'angular-annotation-decorator';
import inject from '../utils/inject';

@annotate( '$q')
export default class DocumentDomainDirective {
  constructor(...args) {
    inject(this, args);
  }
```

**Comment by matAtWork** [comment]
Hmmm.....this is really a question for the acorn-es7-plugin (also mine). Do you know if there's as ESTree specification for annotations?

**Comment by matAtWork** [comment]
There's some discussion of this in https://github.com/estree/estree/issues/44. The issue for nodent is not 'annotations' per se, but how to represent them in such as way as to not break anything else that relies on the EStree specification - notably the parser (acorn) and output code (within nodent, but forked from AString).

**Comment by MatAtBread** [comment]
Closing until estree/acorn become annotation-aware

**Comment by matthiasg** [comment]
Thanks for the feedback.

**Comment by matAtWork** [comment]
I'm part way through a Babel plugin (just because). Maybe this will solve your problem?

**Comment by matAtWork** [comment]
It's here .... https://www.npmjs.com/package/fast-async. I'm not really a babel user, but it might be possible to set up babel to handle your annotations, then get fast-async to asynchronise, and go back to babel to do any remaining transforms. Let me know how it goes.
