### ISSUE TITLE
Using nodent in node js v4.x or v5.x

### ISSUE THREAD

**Issue by Philippe64** [MatAtBread/nodent#14]
Hi Matt,

I try to understand how i can use nodent with node js for Async function /Await

I am trying to make the AFS test working.
**************************
"use nodent-es7";
debugger;
"use strict"
var util = require('util');
var nodent = require('nodent')();
//require 'fs'
var fs = require('fs');
// Get a reference to nodent.asyncify
var asyncify = require('nodent').asyncify;
// asyncify fs
var afs = asyncify(nodent.Thenable)(fs);
//console.log("AFS : ", util.inspect(afs));
var toto = await afs.readFile(__Filename).toString();
console.log("Toto from AFS : " , toto);
*****************************

i thought , i have not to transpile my module , but   

 command : node testAFS.js (or njs) 
give error for await keyword?
***********************
philippe@philippe-ThinkCentre-M58p:~/nodeJS$ node testAFS.js
/home/philippe/nodeJS/testAFS.js:13
var toto = await afs.readFile(__Filename).toString();
                 ^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
**********************************************************

if a try
command : nodent.js testAFS.js
give also  an error " .then is not a function".
*************************************************************************
philippe@philippe-ThinkCentre-M58p:~/nodeJS/node_modules/nodent$ ./nodent.js ../../testAFS.js
Nodent: /home/philippe/nodeJS/testAFS.js(13:11)	'await' used inside non-async function. 'return' value from await is synchronous. See https://github.com/MatAtBread/nodent#differences-from-the-es7-specification
/home/philippe/nodeJS/testAFS.js:10
return afs.readFile(__Filename).toString().then((function ($await_1) {
                    ^

ReferenceError: __Filename is not defined
    at Object.<anonymous> (/home/philippe/nodeJS/testAFS.js:10:21)
    at Module._compile (module.js:425:26)
    at /home/philippe/nodeJS/node_modules/nodent/nodent.js:209:7
    at Object.require.extensions..js (/home/philippe/nodeJS/node_modules/nodent/nodent.js:658:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/philippe/nodeJS/node_modules/nodent/nodent.js:749:10)
    at Module._compile (module.js:425:26)
****************************************************
 
Now if i use your transpiler (cf: try it!  http://nodent.mailed.me.uk/)
i get:
*************************************************
"use nodent-es7";
"use strict";
var util, nodent, fs, asyncify, afs, toto;
debugger;
util = require('util');
nodent = require('nodent')();
fs = require('fs');
asyncify = require('nodent').asyncify;
afs = asyncify(nodent.Thenable)(fs);
return afs.readFile(__Filename).toString().then((function ($await_1) {
    toto = $await_1;
    console.log("Toto fram AFS : ", toto);
}).$asyncbind(this, $error), $error);
*************************************************************
and if i run this : copy/paste to testAFSnodented.js,
command : node testAFSnodented.js,
 it works
*****************************************************
philippe@philippe-ThinkCentre-M58p:~/nodeJS$ node testAFSnodented.js
Toto from AFS :  "use nodent-es7";
debugger;
"use strict"
var util = require('util');
var nodent = require('nodent')();
//require 'fs'
var fs = require('fs');
// Get a reference to nodent.asyncify
var asyncify = require('nodent').asyncify;
// asyncify fs
var afs = asyncify(nodent.Thenable)(fs);
//console.log("AFS : ", util.inspect(afs));
//var toto = await afs.readFile("./test/a.js").toString();
//console.log("Toto from AFS : " , toto);
return afs.readFile(__filename,"utf-8").then(
	(function($await_1){
		toto = $await_1;
		console.log("Toto from AFS : " ,toto);
	}).$asyncbind(this,$error),$error);
****************************************************

So is it a way to avoid transpilation and How?

Sorry for my bad English

Cordially

Philippe

**Comment by MatAtBread** [comment]
Hi Phillipe, you have a couple of points to bear in mind.

You don't need to compile the files in advance, but you can't use 'async' or 'await' in the first file you pass to node - that one has to load nodent:

index.js
````
// Load nodent into Node
require('nodent')();
// Run your main routine
require('./app.js) ;
// The End
````

You _don't_ need to load or require 'nodent' again - just once at the very start of you app.

The `nodent.js` script does this, so you could say `./nodent.js app.js`

Secondly, the reason you got `".then is not a function"` when you tried it is to do with the precedence and binding of the `await` operator. It _must_ be followed by an expression that evaluates to a Promise (such as the return of an async function). In your example, `readFile(filename).toString()' returns a string - you need to use brackets to make it work:

````
// await on the readFile, and then convert it to a string
var toto = (await afs.readFile(__Filename)).toString();
           ^                              ^
````

So your 'app.js' file should look like:
````
"use nodent-es7";
var util = require('util');

//require 'fs'
var fs = require('fs');
// Get a reference to nodent.asyncify
var asyncify = require('nodent').asyncify;
// asyncify fs
var afs = asyncify(nodent.Thenable)(fs);
//console.log("AFS : ", util.inspect(afs));
var toto = (await afs.readFile(__Filename)).toString();
console.log("Toto from AFS : ", toto);
````

Let me know how you get on so I can close this issue if it works.

**Comment by Philippe64** [comment]
Ok thanks for answering.
I think i better understand now

I will try with this schema.

Cordially

Philippe
