### ISSUE TITLE
Add performance comparison with native generators and with regenerator

### ISSUE THREAD

**Issue by epoberezkin** [MatAtBread/nodent#15]
To https://github.com/MatAtBread/nodent#performance
Is it faster to transpile with nodent or to use generators / regenerator?

**Comment by matAtWork** [comment]
Pre-compiling is obviously faster (there's no runtime overhead). Use via 'require()' only compiles on the first instance of each module as Node caches the output, as does generateRequestHandler(), so in these case the overhead (which is pretty small in any case), it only occurs once for each module. Subsequent references are to the compiled ES5/6 code

**Comment by epoberezkin** [comment]
The code is generated at run time

**Comment by matAtWork** [comment]
Once transpiled, Nodent is (still) considerably faster than regenerator and native generators, although this depends a lot on the run-time environment. In particular, V8 v45 and later have much better native performance than earlier versions. Regenerator still underperforms significantly on the browsers I've tried. 

The links in https://github.com/MatAtBread/nodent#performance are probably the best way to judge runtime performance in your environment. You can use the drop-down on http://nodent.mailed.me.uk/#function%20pause()%20%7B%0A%20%20%20%20return%20new%20Promise(function%20(%24return%2C%20%24error)%20%7B%0A%20%20%20%20%20%20%20%20setTimeout(function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%24return(0)%3B%0A%20%20%20%20%20%20%20%20%7D%2C%200)%3B%0A%20%20%20%20%7D)%3B%0A%7D%0A%0Aasync%20function%20doNothing()%20%7B%0A%20%20%20%20return%3B%0A%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20%20%20var%20t%20%3D%20Date.now()%3B%0A%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%2050%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%201000%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20await%20doNothing()%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20await%20pause()%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20Date.now()%20-%20t%3B%0A%7D%0A%0Atest().then(alert)%3B%0A to switch between "ES7", Promises and Generator modes (nodent can generate all three).

**Comment by matAtWork** [comment]
Just trying my browser now (Chrome 47 on Mac OSX), I get numbers around 270ms for "pure ES5" mode, 350ms for "Promise" mode, and 700ms for Generator mode.

**Comment by matAtWork** [comment]
Ok - as I read it (now) the comment is about compilation time, rather than execution time.

For the time-being I've added output to `npm test` to display the overall compilation time, so I can judge changes in performance from one release to the next. This has already allowed an improvement of 20% between v2.3.10 and v2.3.11, however, I take your point - it would be good to know overall compilation speed compared to other solutions.

**Comment by epoberezkin** [comment]
In this case I meant run-time actually :)

**Comment by matAtWork** [comment]
In which case, I'd point you back to https://github.com/MatAtBread/nodent#performance, which allows live comparason between nodent modes (with/without Promises & Generators) and Babel (which uses regenerator) and Traceur.
