### ISSUE TITLE
Suppress "Duplicate 'var ...' in 'anonymous()'" warning

### ISSUE THREAD

**Issue by epoberezkin** [MatAtBread/nodent#17]

**Comment by matAtWork** [comment]
You can disable all logging by passing a {log:function(){}}, e.g.
```
var nodent = require('nodent')({log:function(){}}) ;
```
The warning itself is real - you have two variables declared in your source code that share the same name in the same scope. Nodent hoists them to the top of the scope (to prevent other issues), and so it's warning you that they are actually the same variable.

**Comment by epoberezkin** [comment]
Thanks, that works. I understand that it's real, but it's not worth the effort to avoid redeclaring them in generated code... They should be the same, I just don't want the warnings :)

**Comment by matAtWork** [comment]
NP
