### ISSUE TITLE
nodent-core

### ISSUE THREAD

**Issue by epoberezkin** [MatAtBread/nodent#19]
I'd really appreciate if you could agree to separate nodent-core into a separate npm package, that would be used by nodent.

This way nodent's api wouldn't change at all and I would be able to have a much smaller browser bundle. At the moment nodent's bundle is 186kb (after uglify2).

The core could contain compiler only, no extras.

All I am using is:

```
nodent = require('nodent')({ log: noop });
nodent.compile(code, ''/*filename*/, { promises: true, sourcemap: false }).code;
```
Maybe even go babel's way with plugins, so different transpile modes could be plugins.

**Comment by matAtWork** [comment]
This isn't really an option - most of nodent is compiler (there's around 5% that handles the CLI, but it's not really worth breaking out).
