### ISSUE TITLE
Can we expose the `noUseDirective` compiler option?

### ISSUE THREAD

**Issue by markwylde** [MatAtBread/nodent#32]
If we don't want to use the `'use nodent';` on every file, can we add to the nodent options the `noUseDirective` compiler option.

For use like:
```javascript
require('nodent')({
	noUseDirective: true
})
```

**Comment by markwylde** [comment]
Sorry upon reading more of the documentation I found the option to set compiler options.

```javascript
var nodentMeta = require('nodent') ;
nodentMeta.setDefaultCompileOptions({noUseDirective:true})
nodentMeta()
```

**Comment by matAtWork** [comment]
NP. Glad you found a solution
