### ISSUE TITLE
Exception catching from Express routes

### ISSUE THREAD

**Issue by SirSpunky** [MatAtBread/nodent#33]
Hi,

I really like your approach with nodent, it seems like the right way to go to start using the latest ES7 standards today (async/await). However, I have some problems integrating it with Express. More specifically, I have a problem catching uncaught exceptions from Express routes.

I tried to do a fs.fileRead on a file that didn't exist using async/await (with fs-promise). If I put a try/catch block directly around it in the same Express route, I got a nice error message. However, if I forgot to do that, the page would just keep loading endlessly, rather than give me an error message. I'd much rather I could make Express print a generic error message for uncaught exceptions.

I'm afraid this might be an unsolved limitation of Express, but just thought I would ask if I've missed something. Thanks!

**Comment by matAtWork** [comment]
Although I can't be sure of your exact issue without seeing the code, there are two paths:

The first is the 'global.$error' identifier. This is called when an unhandled exception bubbles all the way back through your code and doesn't encounter a `catch` clause. The default implementation is

````
global.$error = function(ex) { throw ex ; }
````

...which usually results in a node exiting. This is what happens when a top-level 'await' gets rejected.

The second happens when you invoke an async function _without_ awaiting for the result, the unhandled result just disappears.

For express routes, I use a simple wrapper:
````

function asyncRoute(handler) {
    return function(req,res,next) {
    try {
        await handler(req,res,next) ;
   } catch (ex) {
        res.status(500);
        res.write(ex.message);
       res.end() ;
   }

....

app.use(asyncRoute(async function(req,res,next) {
// Handler code goes here
})) ;
````

Let me know if you have any more questions, or close the issue if it explains what you need to know.

**Comment by SirSpunky** [comment]
Thanks a lot for the detailed response! Your wrapper works great when applying it directly to a route function.

However, I tried applying it to a require() instead, so I would only have to apply it once instead of for every route, but I couldn't get that to work. Do you think it would be possible to do something like this?

app.js:
```
app.use(asyncRoute(require('./routes/index')));
```

routes/index.js:    
```
'use nodent';
var router = require('express').Router();

router.use('/readfile', async function (req, res, next) {
    var fs = require('fs-promise'); 
    var result = await fs.readFile('non_existing_file.txt', 'utf8');
    res.render('view_file');
});

module.exports = router;
```

**Comment by matAtWork** [comment]
From the code, I'd imagine the required sequence would be:

app.js:

````
app.use(require('./routes/index'));
````

routes/index.js

````
'use nodent';
var router = require('express').Router();

router.use('/readfile', asyncRoute(async function (req, res, next) {
    var fs = require('fs-promise'); 
    var result = await fs.readFile('non_existing_file.txt', 'utf8');
    res.render('view_file');
}));

module.exports = router;
````

But I've not tried it, so I may have made a mistake.

**Comment by SirSpunky** [comment]
Yeah, you're right. However, I was thinking if it would be possible to wrap the require() instead, so I don't have to wrap it around every route function.

My app will likely have many routes, nested within folders, so it would be great to be able to just wrap them once at the root level, and then not worry about uncaught exceptions anymore. Similar to how you define your normal error handler once in app.js.

But I suspect this is very difficult to accomplish because of how Express uses require() for nested routes. Your solution to wrap every route definitely works, and should be pretty easy to use. I don't want to bother you too much with this, so feel free to close the issue. Thanks a lot for you help!
