### ISSUE TITLE
versionAwareNodentLoader sometimes uses the wrong loader for source files in an app when a module depends on a different version of nodent

### ISSUE THREAD

**Issue by matAtWork** [MatAtBread/nodent#34]
This is probably a result of later versions of npm not placing dependent modules in a strict tree. Need to move to https://github.com/substack/node-resolve rather then assume "../.." is a good place to look.

**Comment by epoberezkin** [comment]
There is require.resolve()

**Comment by MatAtBread** [comment]
Closed by https://github.com/MatAtBread/nodent/pull/35
