### ISSUE TITLE
destructuring causes assignment to undefined

### ISSUE THREAD

**Issue by jnvm** [MatAtBread/nodent#37]
Is nodent meant to allow destructuring?  I've isolated the oddity below. In general, it's preventing me from using the destructuring syntax in some async cases.  Is this expected, or am I misinterpreting things?
run.js:
```
var nodent=require('nodent')()
require("./app.js")
//added to observe transform made
var fs=require("fs")
var c=fs.readFileSync("./app.js")
	,c2=nodent.compile(c,"").code
console.log(c2)
```

app.js:
```
'use nodent';
async function pleaseRun(){
	var {a,b}={a:1,b:2}
	var x=await Promise.resolve(10)
	console.log(a,b,x)
}
pleaseRun()
```

c2 output, transpiled app.js:
```
'use nodent';
function pleaseRun() {
    return (function ($return, $error) {
        var undefined, x;
        undefined = {
            a: 1,
            b: 2
        };
        return Promise.resolve(10).then((function ($await_1) {
            x = $await_1;
            console.log(a, b, x);
            return $return();
        }).$asyncbind(this, $error), $error);
    }).$asyncbind(this, true);
}

pleaseRun();
```
Note the `undefined = {`, which was causing problems for me in less trivial cases.

**Comment by matAtWork** [comment]
Very good catch! Yeah, it's a bug. I'll try and produce a fix in the next couple of days. If you're interested, it's because nodent hoists variable declarations to ensure generated closures have the correct scope, and it doesn't correctly parse destructured `var` declarations.

**Comment by matAtWork** [comment]
Quick workaround: use `let` instead of `var`. `let` declarations do not need to be hoisted as they cannot be referenced prior to declaration, so nodent doesn't fritz them.

**Comment by matAtWork** [comment]
Closed by 31161c832431dc473a76ba2d69ad4d77ddf0c639

Thanks for the report.

**Comment by matAtWork** [comment]
Your example at: http://nodent.mailed.me.uk/#'use%20nodent'%3B%0Aasync%20function%20pleaseRun()%7B%0A%20%20%20%20var%20%7Ba%2Cb%7D%3D%7Ba%3A1%2Cb%3A2%7D%0A%20%20%20%20var%20x%3Dawait%20Promise.resolve(10)%0A%20%20%20%20console.log(a%2Cb%2Cx)%0A%7D%0ApleaseRun()

Now works in Chrome 50

**Comment by jnvm** [comment]
Agreed, and my private case works as well. Thank you very much!
