### ISSUE TITLE
Ask a Question: How can I use the asyncify

### ISSUE THREAD

**Issue by mysyljr** [MatAtBread/nodent#43]
I'm using babel and regenerator, so I don't need to call require('nodent')(). But I want to use a function like nodent.asyncify. Is this compatible? Do I have to call require('nodent')() first?

**Comment by matAtWork** [comment]
This is not really the use case for nodent. Many Promise libraries have a function such as Promisify which will achieve the same kind of things. I'd suggest using one of them from https://www.npmjs.com/search?q=promisify

**Comment by mysyljr** [comment]
That's helpful. Thank you^_^
