### ISSUE TITLE
Nodent writing illegal `const` in `for of` compiled code

### ISSUE THREAD

**Issue by runn1ng** [MatAtBread/nodent#52]
I have an easy ES7 function

````javascript
async function doForEach(doer, array) {
    for (const item of array) {
        await doer(item);
    }
}
````

This is the compiled code ([see on online demo](http://nodent.mailed.me.uk/#%2F%2FES7%20code%0A%0Aasync%20function%20doForEach(doer%2C%20array)%20%7B%0A%20%20%20%20for%20(const%20item%20of%20array)%20%7B%0A%20%20%20%20%20%20%20%20await%20doer(item)%3B%0A%20%20%20%20%7D%0A%7D))

````javascript
//ES7 code
function doForEach(doer, array) {
    return new Promise((function ($return, $error) {
        const item, $iterator_item;
        $iterator_item = [array[Symbol.iterator]()];
        return (function $ForStatement_1_loop($ForStatement_1_exit, $error) {
            function $ForStatement_1_next() {
                return $ForStatement_1_loop($ForStatement_1_exit, $error);
            }
            
            if (!($iterator_item[1] = $iterator_item[0].next()).done && ((item = $iterator_item[1].value) || true)) {
                return doer(item).then((function ($await_3) {
                    return void $ForStatement_1_next.call(this);
                }).$asyncbind(this, $error), $error);
            } else 
                return void $ForStatement_1_exit();
        }).$asyncbind(this).then((function ($await_4) {
            return $return();
        }).$asyncbind(this, $error), $error);
    }).$asyncbind(this));
}
````

However, this is not a legal code. You cannot write `const item, $iterator_item;` and then immediately start writing to them.

For example, browserify will not read this code at all and fail at `ParseError: Unexpected token`.

If I use `for (let item of array)`..., it's OK.

The solution is just use `let` (or `var` is enough, I *think*) in compiling `for..of` iteration.

**Comment by matAtWork** [comment]
Yep, it's a bug. I'll try and post a fix in the next few days.

**Comment by matAtWork** [comment]
Just patched this (see https://github.com/MatAtBread/nodent/compare/issue-52/const-for-of)

I'll merge and re-publish with some other minor fixes as 2.6.4 ASAP.

**Comment by runn1ng** [comment]
This was fast! :+1:

**Comment by MatAtBread** [comment]
My pleasure
