### ISSUE TITLE
Arrow function compilation

### ISSUE THREAD

**Issue by dempfi** [MatAtBread/nodent#54]
Hi I'm using rodent for a while now and recently faced weird issue with compilation of this code 
```js
var x = x || (() => true)
```
Without round brackets this code obviously will not work but will work with them. The problem is nodent compiles this code to 
```js
var x = x || () => true;
```
which fails to run.

_PS: I also strongly disagree with addition of `;`. I believe nodent should do only one thing(compile functions with `async` declaration) and nothing else._

---
[nodent.mailed.me.uk](http://nodent.mailed.me.uk/#var%20x%20%3D%20x%20%7C%7C%20(()%20%3D%3E%20true))

**Comment by matAtWork** [comment]
Thanks - the first issue is a bug. I'll try and patch it ASAP.

The second one is more compiles. Nodent uses acorn to parse your JS into an AST, manipulates the AST to implement async/await, and prints the resulting tree using a JS output routine based on AString. It makes no attempt to maintain your code style. Sourcemaps are used, which will allow you to debug as if you were using the original source to some degree.

Semi-colons are a taste thing. Strictly, JS requires them, but has the concept of "ASI" (automatic semi-colon insertion), which was originally thought a good idea to stop bothering developers with "trivial" syntax errors. In reality, it's a total pain and makes the parser much more complex that it needs to be.

**Comment by dempfi** [comment]
Thanks a lot @matAtWork for really fast reply 👍.
Yeah, I'm familiar with the semicolons issues and because of it I added that PS, anyway the generated code works so I don't see any problem with that.

**Comment by matAtWork** [comment]
Released as version 2.6.5. Additional test included in package:
http://nodent.mailed.me.uk/#var%20a%20%3D%200%20%7C%7C%20(()%3D%3E1)%20%3B%0Avar%20b%20%3D%20()%3D%3E2%20%7C%7C%203%20%3B%0Avar%20c%20%3D%20()%3D%3E4%20%7C%7C%20(()%3D%3E5)%20%3B%0Alog(a()%2Cb()%2Cc())

**Comment by dempfi** [comment]
Whoa so fast. ty man, you are great contributor @matAtWork
