### ISSUE TITLE
Avoid unnecessary recursion when loop iterations don't invoke await

### ISSUE THREAD

**Issue by MatAtBread** [MatAtBread/nodent#56]
As in the following case, where the loop rarely awaits.

```
async function x() {
    for (let i = 0; i < 1000000; i++) {
        if (i == 999999) await a;
    }
}
```

See https://github.com/Microsoft/TypeScript/issues/1664#issuecomment-245994955

**Comment by matAtWork** [comment]
Implemented in https://github.com/MatAtBread/nodent/tree/acorn-4

Confirming compliance and performamce tests
