### ISSUE TITLE
using `for (;;)` fails with `Error: Object.keys called on non-object`

### ISSUE THREAD

**Issue by dessaya** [MatAtBread/nodent#57]
Here is the failing case:

```js
for (;;) {
    await g();
}
```

http://nodent.mailed.me.uk/#for%20(%3B%3B)%20%7B%0A%20%20%20%20await%20g()%3B%0A%7D

Using `while (true)` works as expected.

Thanks!

**Comment by matAtWork** [comment]
Thanks! You're on a roll tonight :)

**Comment by dessaya** [comment]
Thank you for the quick response :D
