### ISSUE TITLE
version 3 - parser error

### ISSUE THREAD

**Issue by SimonDegraeve** [MatAtBread/nodent#60]
Failed to parse:
```js
const fn = () => {};
```

Got this error:
```
Cannot read property 'type' of undefined at nodent/lib/arboriculture.js:2820:37
```

PS: I use the development branch because I love the new `noRuntime` option.

**Comment by matAtWork** [comment]
Wow - I didn't think anyone but me was using v3 yet. You should be aware there are still some issues - mainly with for-in/for-of, especially with let/const index variables. 

Meanwhile...thanks for the report. Simple missed test that a body is not empty. Fixed locally so I'll close here and push later today when I've made some progress with the loops

**Comment by matAtWork** [comment]
FYI, noRuntime _is_ nice, but it is a bit slower, mainly because .bind(this) is slow compared to $asyncbind(this), and the need to wrap async bodies in a try...catch causes de-optimization.

**Comment by matAtWork** [comment]
Oops! I just noticed the PR (I thought it was just a report) and fixed locally. I'll close the PR, but I really appreciate the help.
