### ISSUE TITLE
Error with try/catch/finally

### ISSUE THREAD

**Issue by SimonDegraeve** [MatAtBread/nodent#62]
```js
const fn1 = async () => {
  try {
    throw new Error();
  }
  catch (error) {
    // do nothing
  }
  finally {
    return 'ok';
  }
};
```
Compile to
```js
var fn1 = function fn1() {
  return new Promise(function ($return, $error) {
    try {
      return $error(new Error());
    } catch (error) {
      // do nothing
    } finally {
      return $return('ok');
    }
    return $return();
  }.$asyncbind(undefined));
};
```
**`finally` is never reached**

Same with
```js
const fn2 = async () => {
  try {
    return '1';
  }
  finally {
    return '2';
  }
};
```
```js
var fn2 = function fn2() {
  return new Promise(function ($return, $error) {
    try {
      return $return('1');
    } finally {
      return $return('2');
    }
    return $return();
  }.$asyncbind(undefined));
};
```

**Comment by epoberezkin** [comment]
@SimonDegraeve did you try running this code or do you just think it is never reached because there is a return statement in try?

**Comment by matAtWork** [comment]
Both cases are bugs. 99% of my time is spent checking the async versions work, which in the above case they do (put an await Promise.resolve() at the start of the try block) so these sync cases don't even have a test. I'll attempt a fix for these in v3 - at present it's just a bug

**Comment by SimonDegraeve** [comment]
@epoberezkin yes I did run them.

**Comment by epoberezkin** [comment]
Is the problem here that $return runs multiple times? Because finally is reached and whatever it returns inside finally is returned from the function.

**Comment by SimonDegraeve** [comment]
For `fn1`, If I remove `async` the function returns `ok` (which is expected). With `async` the promise is rejected, it should be resolved with `ok`

**Comment by epoberezkin** [comment]
I see. So finally gets reached, just after the promise is resolved...
