### ISSUE TITLE
Breaks static functions named `get`

### ISSUE THREAD

**Issue by caseyWebb** [MatAtBread/nodent#69]
```bash
echo 'class Foo { static get(v) {return 1} }' | ./nodent.js --out --use=promises
```

output:

```javascript
class Foo {
    static get get(v) {
        return 1;
    }
}
```

**Comment by matAtWork** [comment]
Fixed by https://github.com/MatAtBread/acorn-es7-plugin/releases/tag/1.1.4. Note: The nodent version has not changed (yet), just the dependency acorn-es7-plugin.

**Comment by matAtWork** [comment]
...scrub that. The update has an issue I need to fix before publishing(!)

**Comment by matAtWork** [comment]
Scrub that scrubbing - the issue was elsewhere. acorn-es7-plugin@1.1.5 published that fixes the issue.

**Comment by caseyWebb** [comment]
Thanks for the quick work!
