### ISSUE TITLE
constants can be modified if key name is "arguments"

### ISSUE THREAD

**Issue by djMax** [MatAtBread/nodent#73]
I think perhaps this bug: https://github.com/MatAtBread/fast-async/issues/34 is actually in nodent or lower... For easy reference:

```
console.log({
  arguments: [4567],
});

async function foo() {
  console.log({
    'arguments': [1234],
  });
}

foo();
```

You'll see that the second printed value is not "arguments" but "$args"

**Comment by matAtWork** [comment]
I'm having an issue re-creating this bug. What version of nodent are you testing against?

Here's my test:

http://nodent.mailed.me.uk/#console.log(JSON.stringify(%7B%0A%20%20arguments%3A%20%5B4567%5D%2C%0A%7D))%3B%0A%0Aasync%20function%20foo()%20%7B%0A%20%20console.log(JSON.stringify(%7B%0A%20%20%20%20arguments%3A%20%5B1234%5D%2C%0A%20%20%7D))%3B%0A%7D%0A%0A%2F*%20Outputs%3A%0A%7B%22arguments%22%3A%5B4567%5D%7D%0A%7B%22arguments%22%3A%5B1234%5D%7D%0A*%2F%0Afoo()%3B%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Afalse%2C%22es6target%22%3Afalse%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

**Comment by matAtWork** [comment]
I can see one case (shorthand property members), but either way, I see the issue. I'll fix any I find, but if you find other cases where the identifier `arguments` gets (incorrectly) mangled, please let me know. Thanks for finding and reporting this issue

```
async function x(y){
    console.log({arguments})
}
```
http://nodent.mailed.me.uk/#async%20function%20x(y)%7B%0A%20%20%20%20console.log(%7Barguments%7D)%0A%7D%0A~options~%7B%22mode%22%3A%22lazyThenables%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Afalse%2C%22es6target%22%3Afalse%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

**Comment by djMax** [comment]
(you probably know this, but the recent change to fix the shorthand case doesn't fix my original bug case)

**Comment by djMax** [comment]
```
console.log({
  arguments: [4567],
});

async function foo() {
  const a = {
    arguments: [1234],
  }
  console.log(a);
}

foo();
```

I mistakenly put quotes around it, which works around the problem.

**Comment by MatAtBread** [comment]
Actually, I didn't, because I couldn't make it fail. Is this the test case?

http://nodent.mailed.me.uk/#console.log(JSON.stringify(%7B%0A%20%20%20%20arguments%3A%20%5B4567%5D%0A%7D))%3B%0Aasync%20function%20foo()%20%7B%0A%20%20%20%20console.log(JSON.stringify(%7B%0A%20%20%20%20%20%20%20%20arguments%3A%20%5B1234%5D%0A%20%20%20%20%7D))%3B%0A%7D%0A%0Afoo()%3B%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Afalse%2C%22es6target%22%3Afalse%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

**Comment by djMax** [comment]
So for me, in node, this code:

```
async function foo() {
  console.log({
    arguments: [1234],
  });
}

foo();
```

gets transpiled to:

```
"use strict";

function foo() {
  var $args = arguments;return new Promise(function ($return, $error) {
    console.log({
      $args: [1234]
    });
    return $return();
  }.bind(this));
}

foo();
```

**Comment by djMax** [comment]
(why is that using var instead of let btw?)

**Comment by MatAtBread** [comment]
Are you using Babel/fast-async? Their tree-spec is different from ESTree - I should probably check it works as expected with a Babel AST (although according to ASTexplorer it should be fine).

I prefer `var` to `let` in this context as `arguments` are function-scoped in all cases, and I generally prefer ES5 over ES6 where possible.

**Comment by MatAtBread** [comment]
You have (nonetheless) helped me find the case where arguments are dereferenced in an arrow function inside an async function.

**Comment by djMax** [comment]
Yes, babel/fast-async.

**Comment by MatAtBread** [comment]
Ok, I think I fixed it (in master if you want to pull and check). I'm off to bed (it's 2:30 am here) and I'll put some proper tests together and look at other issues tomorrow.

**Comment by djMax** [comment]
Yep, fixed with a git install and removing ~/.babel.json

**Comment by MatAtBread** [comment]
Fixed by https://github.com/MatAtBread/nodent/issues/73, pending release as 3.0.14

**Comment by matAtWork** [comment]
Fix released in https://github.com/MatAtBread/nodent/releases/tag/3.0.14
