### ISSUE TITLE
Variables defined before await in a comma sequence transpiled out of order

### ISSUE THREAD

**Issue by btakita** [MatAtBread/nodent#74]
See

http://nodent.mailed.me.uk/#async%20function%20foobar()%20%7B%0A%20%20const%20url%20%3D%20%20%60%2Ffoo%2Fbar%60%0A%20%20%20%20%20%20%2C%20response%20%3D%20await%20fetch(url)%0A%7D%0A~options~%7B%22mode%22%3A%22lazyThenables%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Afalse%2C%22es6target%22%3Afalse%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

```
async function foobar() {
  const url =  `/foo/bar`
      , response = await fetch(url)
}
```
Transpiles to:
```
function foobar() {
    return (function ($return, $error) {
        var url, response;
        return fetch(url).then((function ($await_1) {
            url = `/foo/bar`, response = $await_1;
            return $return();
        }).$asyncbind(this, $error), $error);
    }).$asyncbind(this, 0);
}
```

`url` should be set before `fetch`

```
async function foobar() {
  const url =  `/foo/bar`
  const response = await fetch(url)
}
```
Transpiles to:
```
function foobar() {
    return (function ($return, $error) {
        var url, response;
        url = `/foo/bar`;
        return fetch(url).then((function ($await_1) {
            response = $await_1;
            return $return();
        }).$asyncbind(this, $error), $error);
    }).$asyncbind(this, 0);
}
```

**Comment by MatAtBread** [comment]
Excellent catch - that's a bug. I'll try and come up with a fix that isn't too painful

**Comment by MatAtBread** [comment]
The same issue exists in SequenceExpression:
```
async function foobar() {
    var x, url, response;
    x = (url = '/foo/bar'), response = await fetch(url);
}
```
and `Callexpression` arguments, although it will only be an issue if the contain an assignment from an `Awaitexpression`.
```
async function foobar() {
  x(url = '/foo/bar', response = await fetch(url))
}
```

**Comment by matAtWork** [comment]
Closed by https://github.com/MatAtBread/nodent/commit/31aed77ae54a72b04de8680097b1b46ea0673d57 - feel free to pull from the issue-74 branch to test. I'll update tests and publish to npm ASAP

**Comment by matAtWork** [comment]
Fix released in https://github.com/MatAtBread/nodent/releases/tag/3.0.14

**Comment by btakita** [comment]
Thank you!

**Comment by MatAtBread** [comment]
NP. Let me know if you run into problems
