### ISSUE TITLE
Depends on non-existent version of acorn-es7-plugin

### ISSUE THREAD

**Issue by djMax** [MatAtBread/nodent#83]
A verison > 1.1.6 doesn't exist.

**Comment by rainbow-alex** [comment]
Workaround: add `"nodent": "3.0.14"` to your dependencies. 3.0.15 seems to have introduced this problem.

**Comment by aprocom** [comment]
+1

**Comment by matAtWork** [comment]
Oops. Really sorry about that - I missed an "=" after the ">". Fixed in 3.0.16 (3.0.15 unpublished)
