### ISSUE TITLE
It seems a bug, see link: 

### ISSUE THREAD

**Issue by cycold** [MatAtBread/nodent#85]
see: 

It just `await` Number instead a `promise`

if you put ES7 code in chrome > 57  console , it worked, 

> By the way , `nodent` seems  not support Android4.4.4 browser

but using build code , is not working, 

http://nodent.mailed.me.uk/#function%20init()%20%7B%0A%0A%20%20%20%20%20%20%2F%2F%20var%20tick%20%3D%20function(t)%20%7B%0A%20%20%20%20%20%20%2F%2F%20%20%20%20%20return%20new%20Promise(function(resolve%2C%20reject)%7B%0A%20%20%20%20%20%20%2F%2F%20%20%20%20%20%20%20%20%20setTimeout(function%20()%20%7B%0A%20%20%20%20%20%20%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20resolve(t)%0A%20%20%20%20%20%20%2F%2F%20%20%20%20%20%20%20%20%20%7D%2C%20t)%0A%20%20%20%20%20%20%2F%2F%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%2F%2F%20%7D%0A%0A%20%20%20%20%20%20var%20data%20%3D%20'%5B%7B%22age%22%3A%2014%2C%22name%22%3A%20%22Tom%22%7D%2C%20%7B%22age%22%3A%2024%2C%22name%22%3A%20%22Bom%22%7D%2C%20%7B%22age%22%3A%2030%2C%22name%22%3A%20%22Yom%22%7D%5D'%0A%20%20%20%20%20%20var%20dataError%20%3D%20%5B%7B%22age%22%3A%2014%2C%22name%22%3A%20%22Tom%22%7D%2C%20%7B%22age%22%3A%2024%2C%22name%22%3A%20%22Bom%22%7D%5D%0A%0A%20%20%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20async%20function%20getData()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20data%20%3D%20JSON.parse(data)%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20var%20t%20%3D%20await%20tick(1000)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20t%20%3D%20await%201000%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%22tick%22%2C%20t%2C%20data)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20for%20mobile%20debug%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20document.body.innerHTML%20%3D%20%60%3Ccode%3Etick%3A%20%24%7Bt%7D%2C%20%24%7BJSON.stringify(data)%7D%3C%2Fcode%3E%60%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20time%20%3D%20%7B%7D%2C%20t%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20for%20(var%20p%20of%20data)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(p.age%20%3E%2020)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20t%20%3D%20await%20tick(2500)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20t%20%3D%20await%202500%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(p.name%2C%20t)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20document.body.innerHTML%20%2B%3D%20%60%3Cp%3E%24%7Bp.name%7D%3A%24%7Bt%7D%3C%2Fp%3E%60%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20time%5Bp.name%5D%20%3D%20t%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20t%20%3D%20await%20tick(1500)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20t%20%3D%20await%201500%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(p.name%2C%20t)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20document.body.innerHTML%20%2B%3D%20%60%3Cp%3E%24%7Bp.name%7D%3A%24%7Bt%7D%3C%2Fp%3E%60%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20time%5Bp.name%5D%20%3D%20t%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%22time%22%2C%20time)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20document.body.innerHTML%20%2B%3D%20%60%3Cpre%3E%3Ccode%3E%24%7BJSON.stringify(time)%7D%3Ccode%3E%3C%2Fpre%3E%60%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20catch(e)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%22JSON.parse%20failed!%22)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20getData()%0A%20%20%20%20%20%20%20%20%2F%2F%20geterro()%0A%20%20%20%20%20%20%7D%20catch%20(e)%20%7B%0A%20%20%20%20%20%20%20%20alert(e)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20init()%0A%20%20%20%20%7D%20catch(e)%20%7B%0A%20%20%20%20%20%20alert(e)%0A%20%20%20%20%7D%0A~options~%7B%22mode%22%3A%22lazyThenables%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Afalse%2C%22es6target%22%3Afalse%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

**Comment by matAtWork** [comment]
This is documented at https://github.com/MatAtBread/nodent#differences-from-the-es7-specification. For performance reasons, nodent will not wrap `await` arguments in a Promise by default as it is significantly slower. Compile with the `wrapAwait` option if you wish to be able to `await` on non-Promise values.

Please re-open if this is not the cause of the issue.
