### ISSUE TITLE
When using `try/catch` in finally `ReferenceError` is thrown

### ISSUE THREAD

**Issue by le0nik** [MatAtBread/nodent#86]
Demo: http://nodent.mailed.me.uk/#async%20function%20test()%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20await%20normalFn()%3B%0A%20%20%20%20%7D%20finally%20%7B%0A%20%20%20%20%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20await%20throwingFn()%3B%0A%20%20%20%20%20%20%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('err')%3B%20%2F%2F%20%20unreachable%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22native%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

As you can see there is a call to `$Try_3_Catch` inside the `throwingFn().then(..` in `$Try_1_Finally` function, but `$Try_3_Catch` is not defined!

Also for some reason it doesn't even go into the `catch` block if error is thrown in `throwingFn`. It just leaves it wrapped as a sync `try/catch`.

You can see the options i'm using in the demo.
Just in case I'm using `nodent` through `fast-async` babel plugin with these options:

```js
['fast-async', {
  'compiler': {
    'noRuntime': true,
    'es6target': true,
    'promises': true,
  },
}],
```

**Comment by matAtWork** [comment]
I'm not quite sure I can reproduce the issue. When I run the example (see link), it seems to behave as expected:

http://nodent.mailed.me.uk/#async%20function%20normalFn()%20%7B%20return%20%7D%0Aasync%20function%20throwingFn()%20%7B%20JSON.parse(%22*%22)%20%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20try%20%7B%0A%20%20%20%20await%20normalFn()%3B%0A%20%20%7D%20finally%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20await%20throwingFn()%3B%0A%20%20%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20%20%20console.log('err')%3B%20%2F%2F%20unreachable%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Aawait%20test()%20%3B%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

**Comment by le0nik** [comment]
That's because it throws this error in sync. Here's a real world example with an async error.

http://nodent.mailed.me.uk/#async%20function%20normalFn()%20%7B%20return%20%7D%0Aasync%20function%20throwingFn()%20%7B%20return%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20reject(new%20Error('async%20error'))%3B%0A%20%20%20%20%7D)%0A%7D)%20%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20try%20%7B%0A%20%20%20%20await%20normalFn()%3B%0A%20%20%7D%20finally%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20await%20throwingFn()%3B%0A%20%20%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20%20%20console.log(err)%3B%20%2F%2F%20unreachable%20if%20async%20error%20is%20thrown%20in%20%60throwingFn%60%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Aawait%20test()%20%3B%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22native%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

**Comment by matAtWork** [comment]
Ah, ok - thanks for the example. Let me try and work out what's causing it to generate bad code.

**Comment by matAtWork** [comment]
In your above example, you're missing quotes around the `err` in `console.log('err')`. Here's mine, which now works: 

http://nodent.mailed.me.uk/#async%20function%20normalFn()%20%7B%20return%20%7D%0Aasync%20function%20throwingFn()%20%7B%20return%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20reject(new%20Error('async%20error'))%3B%0A%20%20%20%20%7D)%0A%7D)%20%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20try%20%7B%0A%20%20%20%20await%20normalFn()%3B%0A%20%20%7D%20finally%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20await%20throwingFn()%3B%0A%20%20%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20%20%20console.log('err')%3B%20%2F%2F%20unreachable%20if%20async%20error%20is%20thrown%20in%20%60throwingFn%60%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Aawait%20test()%20%3B%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22native%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

It does call into question where the `ReferenceError` to `err` in your example generates the message it does. At best it's unhelpful, at worst it's a bug, so I'll try and understand exactly the flow at that point.

**Comment by matAtWork** [comment]
No - ignore that, `err` is perfectly well defined as the parameter to catch(). I'll dig a bit deeper - something is very odd

**Comment by matAtWork** [comment]
I think I've fixed this case. The update (v3.0.18) is now on nodent.mailed.me.uk. Please check it fixes your issue (if you want to test locally grab a copy of https://github.com/MatAtBread/nodent/tree/fix/try-finally-try-catch)

I'll complete my test suite and assuming you're happy and it passes everything else, I'll ship v3.0.18 ASAP. Let me know

**Comment by le0nik** [comment]
Thank you for the fast reply! Testing the fix now.

**Comment by le0nik** [comment]
Can confirm that this fix is working. Although i've stumbled on another(kind of related bug). Should I open a new issue for it?

**Comment by MatAtBread** [comment]
Yep, that's a different cause, so I'll have to investigate. Did v3.0.18 fix your initial issue?

**Comment by le0nik** [comment]
Yes, it did. Thank you!
