### ISSUE TITLE
Error is swallowed if it's rethrown in the `catch` block and there is a `finally` with an async handler

### ISSUE THREAD

**Issue by le0nik** [MatAtBread/nodent#88]
Demo:
http://nodent.mailed.me.uk/#async%20function%20func1()%20%7B%20throw%20new%20Error('func1%20error')%3B%20%7D%0Aasync%20function%20func2()%20%7B%20return%3B%20%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20try%20%7B%0A%20%20%20%20await%20func1()%3B%0A%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20throw%20err%3B%20%2F%2F%20rethrowing%20error%20here%0A%20%20%7D%20finally%20%7B%0A%20%20%20%20await%20func2()%3B%0A%20%20%7D%0A%7D%0A%0Aasync%20function%20runTest()%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20await%20test()%3B%0A%20%20%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20this%20catch%20is%20not%20reached%20although%20err%20was%20rethrown%20inside%20%60test()%60%20catch%20block%0A%20%20%20%20%20%20%20%20console.log('err%20in%20runTest()'%2C%20err)%3B%20%0A%20%20%20%20%7D%0A%7D%0A%0Aawait%20runTest()%3B~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22native%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

As you can see the error is re-thrown on line 8 but it's swallowed and never gets to the line 19 because of the finally block.

**Comment by matAtWork** [comment]
Released in v3.0.18
