### ISSUE TITLE
Unexpected character '#'

### ISSUE THREAD

**Issue by callblueday** [MatAtBread/nodent#92]
I have a warning report when i use nodent

```bash
Module parse failed: 
xxx/node_modules/.3.0.20@nodent/nodent.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node

```

how could i fix it ?

**Comment by matAtWork** [comment]
Can you give me more details? Which version of Node, what you are loading nodent with (is it webpack?). The error is because nodent.js is runnable from the command line - the `#!` prefix is a defacto standard and most node-related things simply ignore it

**Comment by callblueday** [comment]
@matAtWork! Thanks for your reply!  My env is 
```
node: 7.2.0
npm: 3.10.9
```
and i load nodent with webpack2. It seems i can ignore the warning report.

**Comment by matAtWork** [comment]
I believe it's an issue with webpack. When I use webpack, I use a specialised loader (nodent-loader) which is (probably) out of date. You could raise an issue on webpack ("Make webpack ignore the standard bash prefix") - there may be an answer already.

Feel free to re-open if you think I can help further.

**Comment by callblueday** [comment]
Thanks a lot!
