### ISSUE TITLE
How to compile from one folder to another folder?

### ISSUE THREAD

**Issue by trusktr** [MatAtBread/nodent#96]
For example, with Buble I can do `buble -i someFolder -o outPutFolder` to compile whole directories. The output file tree structure matches the input file tree structure.

Is there an option like this for nodent? Or do I need to write my own to traverse the file tree?

What I'd like to do is run nodent first, then run buble on the output files. If I run buble first, it doesn't understand `async` to it throws an error.

**Comment by matAtWork** [comment]
No, nodent doesn't walk trees. The `--dest` option can be used to specify a different destination for output, so `./nodent.js --dest=dist/ --noruntime a.js` will produce `dist\a.js`. If you wanted to add this, the CLI compiler is at https://github.com/MatAtBread/nodent/blob/master/nodent.js#L643. PRs are always welcome.

Alternatively, require `nodent-compiler` and write a little thing to walk a tree and compile for you.

I'm not very familiar with Buble, but I know from previous work on Webpack and Babel that getting all the options and extensions to work together isn't easy.
